
DROP TABLE IF EXISTS books;
CREATE TABLE books (id INTEGER PRIMARY KEY AUTOINCREMENT, title VARCHAR(255), author VARCHAR(255), price DECIMAL, stock VARCHAR(20), format VARCHAR(20));

INSERT INTO books (title, author, price, stock, format) VALUES

("SQL in Easy Steps", "Mike McGrath", "10.99", "In Stock", "PaperBack"),
("SQL in 10 Minutes, Sams Teach Yourself", "Ben Forta", "18.99", "In Stock", "PaperBack"),
("Microsoft SQL Server 2008 All-in-one Desk Reference For Dummies", "Robert D. Schneider", "29.99", "In Stock", "PaperBack"),
("SQL For Dummies", "Allen G. Taylor", "21.99", "In Stock", "PaperBack"),
("SQL", "Rick Morelan", "10.99", "In Stock", "PaperBack"),
("Oracle 11G", "Joan Casteel", "58.99", "In Stock", "PaperBack"),
("SQL", "Forrest Houlette", "21.99", "In Stock", "PaperBack"),
("SQL", "Jurgen Marsch", "42.99", "In Stock", "PaperBack"),
("SQL", "Jurgen Marsch", "42.99", "In Stock", "PaperBack"),
("Querying Microsoft SQL Server 2012", "Itzik Ben-Gan", "43.99", "In Stock", "PaperBack"),
("Administering Microsoft SQL Server 2012 Databases", "Orin Thomas", "43.99", "In Stock", "PaperBack"),
("SQL", "James R. Groff", "51.68", "In Stock", "PaperBack"),
("Sql", "Jack Hursch", "17.95", "In Stock", "PaperBack"),
("SQL", "Chris Fehily", "27.99", "In Stock", "PaperBack"),
("Microsoft SQL Server 2012 T-SQL Fundamentals", "Itzik Ben-Gan", "30.99", "In Stock", "PaperBack"),
("SQL", "Susan Sales Harkins", "39.49", "In Stock", "PaperBack"),
("SQL", "James R. Groff", "48.99", "In Stock", "PaperBack"),
("SQL", "Michael J. Donahoo", "22.99", "In Stock", "PaperBack"),
("Pro SQL Server Internals", "Dmitri Korotkevitch", "35.50", "Out of Stock", "PaperBack"),
("SQL", "Chris Fehily", "34.48", "Out of Stock", "PaperBack"),
("Oracle 12c", "Joan Casteel", "69.99", "Out of Stock", "PaperBack"),
("Data Analysis Using SQL and Excel", "Gordon S. Linoff", "33.99", "Out of Stock", "PaperBack"),
("Implementing a Data Warehouse with Microsoft SQL Server 2012", "Dejan Sarka", "43.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2014 Unleashed", "Ray Rankins", "36.99", "Out of Stock", "PaperBack"),
("SQL Queries for Mere Mortals", "John L. Viescas", "30.99", "Out of Stock", "PaperBack"),
("Head First SQL", "Lynn Beighley", "35.50", "Out of Stock", "PaperBack"),
("SQL Pocket Guide", "Jonathan Gennick", "10.50", "Out of Stock", "PaperBack"),
("The Definitive Guide to Dax", "Alberto Ferrari", "30.99", "Out of Stock", "PaperBack"),
("SQL in 24 Hours, Sams Teach Yourself", "Ryan Stephens", "24.99", "Out of Stock", "PaperBack"),
("SQL Server Execution Plans", "Grant Fritchey", "19.99", "Out of Stock", "PaperBack"),
("Professional Microsoft SQL Server 2014 Administration", "Adam Jorgensen", "36.99", "Out of Stock", "PaperBack"),
("T-SQL Querying", "Itzik Ben-Gan", "36.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2012 Bible", "Adam Jorgensen", "39.99", "Out of Stock", "PaperBack"),
("Knight's Microsoft SQL Server 2012 Integration Services 24-Hour Trainer", "Brian Knight", "33.99", "Out of Stock", "PaperBack"),
("Practical SQL Queries for Microsoft SQL Server 2008 R2", "Arthur D. Tennick", "39.99", "Out of Stock", "PaperBack"),
("Sams Teach Yourself SQL in 24 Hours", "Ryan Stephens", "21.99", "Out of Stock", "PaperBack"),
("Learning SQL", "Alan Beaulieu", "26.50", "In Stock", "PaperBack"),
("SQL Cookbook", "Anthony Molinaro", "28.50", "In Stock", "PaperBack"),
("OCA Oracle Database SQL Certified Expert Exam Guide: Exam 1Z0-047", "Steve O'Hearn", "51.99", "In Stock", "PaperBack"),
("Delivering Business Intelligence with Microsoft SQL Server 2012", "Brian Larson", "36.99", "In Stock", "PaperBack"),
("Microsoft SQL Server 2012 Reporting Services", "Brian Larson", "36.99", "In Stock", "PaperBack"),
("Microsoft SQL Server 2008 Reporting Services Step by Step", "Stacia Misner", "30.99", "In Stock", "PaperBack"),
("Professional Microsoft SQL Server 2014 Integration Services", "Brian Knight", "36.99", "In Stock", "PaperBack"),
("SQL All-in-One For Dummies", "Allen G. Taylor", "27.99", "In Stock", "PaperBack"),
("Microsoft SQL Server 2012 Analysis Services", "Marco Russo", "36.99", "In Stock", "PaperBack"),
("Beginning SQL 2012 Joes 2 Pros Volume 1", "Rick Morelan", "11.99", "In Stock", "PaperBack"),
("Microsoft SQL Server 2012 Step by Step", "Patrick LeBlanc", "30.99", "In Stock", "PaperBack"),
("Sams Teach Yourself Microsoft SQL Server T-SQL in 10 Minutes", "Ben Forta", "18.99", "In Stock", "PaperBack"),
("Beginning Microsoft SQL Server 2012 Programming", "Professor Paul Atkinson", "26.99", "In Stock", "PaperBack"),
("Microsoft SQL Server 2014 Query Tuning & Optimization", "Benjamin Nevarez", "35.99", "In Stock", "PaperBack"),
("OCA Oracle Database 12c SQL Fundamentals I Exam Guide (Exam 1Z0-061)", "Roopesh Ramklass", "47.91", "In Stock", "PaperBack"),
("Oracle PL/SQL Programming", "Steven Feuerstein", "46.50", "In Stock", "PaperBack"),
("Beginning Ssrs 2012 Joes 2 Pros (R)", "Kathi Kellenberger", "12.99", "In Stock", "PaperBack"),
("Oracle PL/SQL Language Pocket Reference", "Steven Feurstein", "11.50", "In Stock", "PaperBack"),
("Exam 70-462 Administering Microsoft SQL Server 2012 Databases", "Microsoft Official Academic Course", "111.99", "Out of Stock", "PaperBack"),
("Exam 70-461 Querying Microsoft SQL Server 2012", "Microsoft Official Academic Course", "111.99", "Out of Stock", "PaperBack"),
("The Microsoft Data Warehouse Toolkit", "Joy Mundy", "33.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 High Availability", "Hemantgiri S. Goswami", "30.99", "Out of Stock", "PaperBack"),
("Oracle SQL by Example", "Alice Rischert", "43.99", "Out of Stock", "PaperBack"),
("Oracle Sql High Performance Tuning", "Guy Harrison", "33.99", "Out of Stock", "PaperBack"),
("The Oracle PL/SQL by Example", "Carrie Anderson", "31.99", "Out of Stock", "PaperBack"),
("XML and SQL", "Daniel K. Appelquist", "24.99", "Out of Stock", "PaperBack"),
("Oracle PL/SQL", "Benjamin Rosenzweig", "24.99", "Out of Stock", "PaperBack"),
("DB2 SQL Tuning Tips for Z/OS Developers", "Tony Andrews", "24.99", "Out of Stock", "PaperBack"),
("Microsoft Sql Server 2000 Database Administrator's Guidebook", "Carl H. Speshock", "24.99", "Out of Stock", "PaperBack"),
("Oracle SQL and PL/SQL Handbook", "John Adolph Palinski", "33.99", "Out of Stock", "PaperBack"),
("Database Unit Testing for SQL Server Using tSQLt", "Dennis Lloyd", "24.99", "Out of Stock", "PaperBack"),
("Microsoft Transact-SQL", "Jeffrey Garbus", "37.99", "Out of Stock", "PaperBack"),
("Oracle SQL Developer Data Modeler for Database Design Mastery", "Heli Helskyaho", "46.99", "Out of Stock", "PaperBack"),
("Sayles: Qmf - How to Use Query Management Facility with Db2 & Sql/Ds", "JS SAYLES", "28.95", "Out of Stock", "PaperBack"),
("The Essence of Sql", "D Rozenshtein", "15.99", "Out of Stock", "PaperBack"),
("MCITP SQL Server 2005 Database Administration", "Darril Gibson", "48.93", "Out of Stock", "PaperBack"),
("Datenbank-Engineering", "Alfred Moos", "42.99", "Out of Stock", "PaperBack"),
("SQL 3 Complete, Really", "Peter Gulutzan", "50.48", "Out of Stock", "PaperBack"),
("SQL Server 2000", "Dejan Sunderic", "36.99", "Out of Stock", "PaperBack"),
("SQL Server Source Control Basics", "Robert Sheldon", "19.99", "Out of Stock", "PaperBack"),
("SQL Queries 2012 Joes 2 Pros (R) Volume 4", "Rick Morelan", "24.79", "Out of Stock", "PaperBack"),
("Wrox SQL Server 2005", "Robert Vieira", "65.00", "Out of Stock", "PaperBack"),
("My SQL", "John W. Horn", "17.99", "Out of Stock", "PaperBack"),
("SQL Server 2000 Stored Procedure Programming", "Dejan Sunderic", "32.99", "Out of Stock", "PaperBack"),
("Troubleshooting SQL", "Forrest Houlette", "29.99", "Out of Stock", "PaperBack"),
("SQL Server 112 Success Secrets - 112 Most Asked Questions on SQL Server - What You Need to Know", "Martha Clemons", "20.99", "Out of Stock", "PaperBack"),
("SQL Bearbeitung Relationaler Datenbanken", "Wolf-Michael Kahler", "42.99", "Out of Stock", "PaperBack"),
("Oracle PL/SQL for DBAs", "Steven Feuerstein", "31.99", "Out of Stock", "PaperBack"),
("SQL Antipatterns", "Bill Karwin", "24.99", "Out of Stock", "PaperBack"),
("Sql Server 7 Olap Developer's Guide", "William C. Amo", "36.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Azure Enterprise Application Development", "Jayaram Krishnaswamy", "30.99", "Out of Stock", "PaperBack"),
("What's New in SQL Server 2012: Unleash the New Features of SQL Server 2012", "Rachel Clements", "21.99", "Out of Stock", "PaperBack"),
("SQL Injection Attack and Countermeasures", "Subi Khan", "39.00", "Out of Stock", "PaperBack"),
("Datenbanken Und SQL", "Edwin Schicker", "42.99", "Out of Stock", "PaperBack"),
("PL/SQL Trainer Auf Basis Von JSP Und Elml", "Rechs Markus", "28.00", "Out of Stock", "PaperBack"),
("SQL Server 2000 Black Book", "Patrick Dalton", "50.52", "Out of Stock", "PaperBack"),
("Learn SQL Server 2000 Administration", "Jeffrey Garbus", "25.99", "Out of Stock", "PaperBack"),
("Transact-SQL User-defined Functions", "Andrew C. Novick", "43.50", "Out of Stock", "PaperBack"),
("The Best Damn Exchange, SQL and IIS Book Period", "Henrik Walther", "40.99", "Out of Stock", "PaperBack"),
("The PostgreSQL Reference Manual: SQL Language Reference v. 1", "Postgresql Global Development Group", "32.00", "Out of Stock", "PaperBack"),
("Oracle 11G", "Joan Casteel", "49.99", "Out of Stock", "PaperBack"),
("Oracle Database 12c PL/SQL Programming", "Michael McLaughlin", "52.99", "Out of Stock", "PaperBack"),
("Getting Started with SQL Server 2014 Administration", "Gethyn Ellis", "16.99", "Out of Stock", "PaperBack"),
("Advanced SQL Functions in Oracle 10g", "Dr. Richard Earp", "48.99", "Out of Stock", "PaperBack"),
("Building Integrated Business Intelligence Solutions with SQL Server 2008 R2 and Office 2010", "Philo B. Janus", "38.99", "Out of Stock", "PaperBack"),
("Beginning Spatial with SQL Server 2008", "Alastair Aitchison", "43.44", "Out of Stock", "PaperBack"),
("Beginning SQL Server 2008 Administration", "Robert Walters", "35.50", "Out of Stock", "PaperBack"),
("Pro SQL Server 2008 Policy-based Management", "Ken Simmons", "47.50", "Out of Stock", "PaperBack"),
("Oracle and PL/SQL Recipes", "Josh Juneau", "31.50", "Out of Stock", "PaperBack"),
("Foundations of SQL Server 2008 R2 Business Intelligence", "Guy Fouche", "39.50", "Out of Stock", "PaperBack"),
("Pro SQL Azure", "Scott Klein", "39.50", "Out of Stock", "PaperBack"),
("Pro Oracle SQL 2013", "Karen Morton", "32.50", "Out of Stock", "PaperBack"),
("Expert SQL Server 2008 Development", "Adam Machanic", "43.50", "Out of Stock", "PaperBack"),
("A Guide to Sql", "Philip Pratt", "29.99", "Out of Stock", "PaperBack"),
("MCSE Guide to SQL Server 2000 Administration", "Mathew Raftree", "87.00", "Out of Stock", "PaperBack"),
("Learning Oracle SQL and Pl/SQL", "Rajeeb C. Chatterjee", "17.50", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2014 Business Intelligence Development Beginner's Guide", "Reza Rad", "30.99", "Out of Stock", "PaperBack"),
("Protecting SQL Server Data", "John Magnabosco", "19.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server Handbook", "Ken England", "35.00", "Out of Stock", "PaperBack"),
("Writing Stored Procedures with Microsoft SQL Server", "Matthew Shepker", "28.99", "Out of Stock", "PaperBack"),
(".Net Enterprise Design With Visual Basic .Net and SQL Server 2000", "Jimmy Nilsson", "36.50", "Out of Stock", "PaperBack"),
("MS SQL Server 2000 Data Transformation Services (DTS)", "Tim Peterson", "36.50", "Out of Stock", "PaperBack"),
("Sams Teach Yourself Transact-SQL in 21 Days", "David S. Solomon", "28.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2000 DBA Survival Guide", "Mark Spenik", "36.50", "Out of Stock", "PaperBack"),
("SQL Server 2005", "Ross Mistry", "28.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005", "Ray Rankins", "42.99", "Out of Stock", "PaperBack"),
("ALS Microsoft SQL Server 2000 System Administration", "Microsoft Official Academic Course", "37.99", "Out of Stock", "PaperBack"),
("SQL For Dummies", "Allen G. Taylor", "21.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2012 Unleashed", "Ray Rankins", "36.99", "Out of Stock", "PaperBack"),
("Virtualizing SQL Server with VMware", "Michael Corey", "27.99", "Out of Stock", "PaperBack"),
("SQL Server Forensic Analysis", "Kevvie Fowler", "36.99", "Out of Stock", "PaperBack"),
("Hitchhiker's Guide to Visual Studio and SQL Server Yukon", "William R. Vaughn", "40.99", "Out of Stock", "PaperBack"),
("SQL Server 2005 Practical Troubleshooting", "Ken Henderson", "36.99", "Out of Stock", "PaperBack"),
("SQL Queries for Mere Mortals", "Michael J. Hernandez", "46.99", "Out of Stock", "PaperBack"),
("Practical Business Intelligence with SQL Server 2005", "Roger Toren", "40.99", "Out of Stock", "PaperBack"),
("SQL Server Fundamentals for the Accidental DBA LiveLessons (video Training)", "Eric Johnson", "94.02", "Out of Stock", "PaperBack"),
("The Guru's Guide to Transact SQL", "Ken Henderson", "43.99", "Out of Stock", "PaperBack"),
("Essential SQL Server 2000", "Buck Woody", "24.99", "Out of Stock", "PaperBack"),
("A Guide to the SQL Standard", "C. J. Date", "29.99", "Out of Stock", "PaperBack"),
("The Practical SQL Handbook", "Judith S. Bowman", "43.99", "Out of Stock", "PaperBack"),
("The Guru's Guide to SQL Server Architecture and Internals", "Ken Henderson", "40.99", "Out of Stock", "PaperBack"),
("Beginning SQL Joes 2 Pros", "Rick Morelan", "11.99", "Out of Stock", "PaperBack"),
("Professional SQL Server 2000 DTS (Data Transformation Services)", "Mark Chaffin", "35.99", "Out of Stock", "PaperBack"),
("Professional SQL Server Analysis Services 2005 with MDX", "Sivakumar Harinath", "31.99", "Out of Stock", "PaperBack"),
("SQL Instant Reference", "Martin Gruber", "21.99", "Out of Stock", "PaperBack"),
("Joe Celko's Analytics and OLAP in SQL", "Joe Celko", "33.99", "Out of Stock", "PaperBack"),
("Oracle Database 10g: Student Manual", "Course Technology", "53.99", "Out of Stock", "PaperBack"),
("Oracle Database 10g: Student Manual", "Course Technology", "130.99", "Out of Stock", "PaperBack"),
("SQL Fundamentals", "Course Technology", "17.99", "Out of Stock", "PaperBack"),
("Mastering Oracle SQL", "Sanjay Mishra", "28.50", "Out of Stock", "PaperBack"),
("Portable DBA: SQL Server", "Damir Bersinic", "19.99", "Out of Stock", "PaperBack"),
("Oracle8i Certified Professional SQL and PL/SQL Exam Guide", "Jason Couchman", "36.99", "Out of Stock", "PaperBack"),
("SQL Server 2000 Backup and Recovery", "Anil Desai", "32.99", "Out of Stock", "PaperBack"),
("Pro SQL Server 2008 XML", "Michael Coles", "51.45", "Out of Stock", "PaperBack"),
("SQL Injection Attacks and Possible Remedies", "Jayeeta Majumder", "38.00", "Out of Stock", "PaperBack"),
("The Art of SQL Server FILESTREAM", "Jacob Sebastian", "19.99", "Out of Stock", "PaperBack"),
("Expert Cube Development with Microsoft SQL Server 2008 Analysis Services", "Chris Webb", "30.99", "Out of Stock", "PaperBack"),
("Java Und SQL. Bestphone Call-Handling", "Thomas Hillen", "24.90", "Out of Stock", "PaperBack"),
("SQL Fundamentals", "John J. Patrick", "43.99", "Out of Stock", "PaperBack"),
("Optimization of SQL Queries for Parallel Machines", "Waqar Hasan", "49.99", "Out of Stock", "PaperBack"),
("MS SQL Server Interview Questions, Answers, and Explanations", "Terry Sanchez-Clark", "25.00", "Out of Stock", "PaperBack"),
("Dynamic Management Views", "Louis Davidson", "19.99", "Out of Stock", "PaperBack"),
("Two Minute SQL Server Stumpers: v. 6", "Various", "8.99", "Out of Stock", "PaperBack"),
("SQL Server Concurrency", "Kalen Delaney", "19.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 R2 Administration Cookbook", "Satya Shyam K. Jayanty", "33.99", "Out of Stock", "PaperBack"),
("SQL Server Backup and Restore", "Shawn McGehee", "19.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Step by Step", "Mike Hotek", "30.99", "Out of Stock", "PaperBack"),
("SQL Server Interview Questions", "Shiv Prasad Koirala", "11.50", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005 Integration Services Step by Step", "Hitachi Consulting", "27.99", "Out of Stock", "PaperBack"),
("SQL Guide (Speedy Study Guides", "Speedy Publishing LLC", "5.35", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 R2 Unleashed", "Ray Rankins", "36.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2000 Analysis Services Step by Step", "Microsoft Corporation", "24.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2000 DTS Step by Step", "Carl Rabeler", "24.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005", "", "24.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2000 Reporting Services Step by Step", "Stacia Misner", "24.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2000 High Availability", "Microsoft Corporation", "30.99", "Out of Stock", "PaperBack"),
("Pro T-SQL 2012 Programmer's Guide", "Michael Coles", "39.50", "Out of Stock", "PaperBack"),
("Pro SQL Server 2012 Practices", "C. Shaw", "29.50", "Out of Stock", "PaperBack"),
("SQL Server 2012 Data Integration Recipes", "Adam Aspin", "29.50", "Out of Stock", "PaperBack"),
("Pro SQL Server 2008 Integration Services", "James Wightman", "39.49", "Out of Stock", "PaperBack"),
("Pro Oracle SQL", "Karen Morten", "39.50", "Out of Stock", "PaperBack"),
("PL/SQL for Students", "Dr (Prof) M M Alshomrani", "17.00", "Out of Stock", "PaperBack"),
("SQL Server 2000", "Harshad Nadkarni", "29.99", "Out of Stock", "PaperBack"),
("Data Analysis Using SQL and Excel", "Gordon S. Linoff", "30.99", "Out of Stock", "PaperBack"),
("Inside Relational Databases with Examples in SQL Server", "Mark Whitehorn", "24.50", "Out of Stock", "PaperBack"),
("Basics of SQL Injection Analysis, Detection and Prevention", "Halde Jagdish", "28.00", "Out of Stock", "PaperBack"),
("Professional Microsoft Sharepoint 2007 Reporting with SQL Server 2008 Reporting Services", "Jacob J. Sanford", "39.99", "Out of Stock", "PaperBack"),
("MCTS", "Joseph L. Jorden", "31.99", "Out of Stock", "PaperBack"),
("Professional SQL Server 2005 Administration", "Brian Knight", "31.99", "Out of Stock", "PaperBack"),
("SQL Server 2008 Administration", "Tom Carpenter", "47.50", "Out of Stock", "PaperBack"),
("Exam 70-431 Microsoft SQL Server 2005 Implementation and Maintenance Lab Manual", "Microsoft Official Academic Course", "37.99", "Out of Stock", "PaperBack"),
("Exam 70-431", "Microsoft Official Academic Course", "119.99", "Out of Stock", "PaperBack"),
("Expert SQL Server 2005 Integration Services", "Brian Knight", "31.99", "Out of Stock", "PaperBack"),
("Exam 70-443 & 70-450", "Microsoft Official Academic Course", "119.99", "Out of Stock", "PaperBack"),
("Exam 70-432 Microsoft SQL Server 2008 Implementation and Maintenance Lab Manual", "Microsoft Official Academic Course", "37.99", "Out of Stock", "PaperBack"),
("Exam 70-432", "Microsoft Official Academic Course", "119.99", "Out of Stock", "PaperBack"),
("Exam 70-443 & 70-450 Microsoft SQL Server Database Design and Optimization Lab Manual", "Microsoft Official Academic Course", "37.99", "Out of Stock", "PaperBack"),
("Professional Microsoft SQL Server 2008 Reporting Services", "Paul Turley", "42.50", "Out of Stock", "PaperBack"),
("Pro Full-Text Search in SQL Server 2008", "Hillary Cotter", "39.49", "Out of Stock", "PaperBack"),
("Ultra-Fast ASP.NET", "Rick Kiessig", "39.49", "Out of Stock", "PaperBack"),
("Pro SQL Server 2008 Analysis Services", "Philo B. Janus", "35.50", "Out of Stock", "PaperBack"),
("SQL in a Nutshell", "Kevin Kline", "31.99", "Out of Stock", "PaperBack"),
("SQL Hacks", "Andrew Cumming", "21.50", "Out of Stock", "PaperBack"),
("Develop Business Applications with Sharepoint 2010, SQL 2012, and Lightswitch", "David Feldman", "35.50", "Out of Stock", "PaperBack"),
("Pro SQL Server 2005 Integration Services", "James Wightman", "39.49", "Out of Stock", "PaperBack"),
("Pro SQL Server Disaster Recovery", "James Luetkehoelter", "58.92", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Analytics and Data Visualization", "Doug Harts", "38.99", "Out of Stock", "PaperBack"),
("Beginning Oracle SQL 2014", "Tim Gorman", "29.50", "Out of Stock", "PaperBack"),
("SQL Server Query Performance Tuning 2014", "Sajal Dam", "35.50", "Out of Stock", "PaperBack"),
("Pro Spatial with SQL Server 2012", "Alastair Aitchison", "47.50", "Out of Stock", "PaperBack"),
("Pro SQL Server 2012 Relational Database Design and Implementation", "Louis Davidson", "47.50", "Out of Stock", "PaperBack"),
("SQL Server 2012 Query Performance Tuning 20123", "Grant Fritchey", "47.50", "Out of Stock", "PaperBack"),
("Study Guide for 1z0-146", "Matthew Morris", "8.27", "Out of Stock", "PaperBack"),
("Pro SQL Server 2005 High Availability", "Allan Hirt", "73.88", "Out of Stock", "PaperBack"),
("Beginning SQL Server 2000 Programming", "Robin Dewson", "35.49", "Out of Stock", "PaperBack"),
("Beginning SQL Server 2000 for Visual Basic Developers", "Thearon Willis", "31.49", "Out of Stock", "PaperBack"),
("Beginning SQL Server 2000 DBA", "Tony Bain", "39.49", "Out of Stock", "PaperBack"),
("SQL Server 2000 Stored Procedures Handbook", "Tony Bain", "31.49", "Out of Stock", "PaperBack"),
("Pro SQL Server 2005 Assemblies", "Robin Dewson", "39.49", "Out of Stock", "PaperBack"),
("Beginning SQL Server 2005 for Developers", "Robin Dewson", "39.49", "Out of Stock", "PaperBack"),
("Pro SQL Server Reporting Services", "Rodney Landrum", "31.49", "Out of Stock", "PaperBack"),
("Beginning SQL Server 2005 Express for Developers", "Robin Dewson", "31.49", "Out of Stock", "PaperBack"),
("Beginning SQL Queries", "Clare Churcher", "27.49", "Out of Stock", "PaperBack"),
("Beginning SQL Server 2008 for Developers", "Robin Dewson", "39.49", "Out of Stock", "PaperBack"),
("Pro SQL Server 2005 Reporting Services", "Rodney Landrum", "31.49", "Out of Stock", "PaperBack"),
("Pro SQL Server 2005", "Louis Davidson", "39.49", "Out of Stock", "PaperBack"),
("Pro SQL Server 2005 High Availability", "Allan Hirt", "73.88", "Out of Stock", "PaperBack"),
("From Access to SQL Server", "Russell Sinclair", "39.49", "Out of Stock", "PaperBack"),
("Data Mining and Statistical Analysis Using SQL", "John Lovett, Jr.", "39.49", "Out of Stock", "PaperBack"),
("Designing a Database Server Infrastructure Using Microsoft SQL Server 2005", "J. C. Mackin", "36.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 T-SQL Fundamentals", "Itzik Ben-Gan", "30.99", "Out of Stock", "PaperBack"),
("SQL Server 2000 Web Application Developer's Guide", "Craig Utley", "35.99", "Out of Stock", "PaperBack"),
("Erfolgreiche Datenbankanwendung Mit Sql3", "Jorg Fritze", "42.99", "Out of Stock", "PaperBack"),
("Oracle PL/SQL Tips and Techniques", "Richard Neimic", "25.99", "Out of Stock", "PaperBack"),
("Using SQL Windows and Centura", "Sanjiv Purba", "29.99", "Out of Stock", "PaperBack"),
("DB2 SQL 75+ Tuning Tips for Developers", "Tony Andrews", "13.50", "Out of Stock", "PaperBack"),
("Alternative DNS Servers", "Jan-Piet Mens", "12.95", "Out of Stock", "PaperBack"),
("Two Minute SQL Server Stumpers: v. 5", "Steve Jones", "8.99", "Out of Stock", "PaperBack"),
("Oracle Advanced PL/SQL Developer Professional Guide", "Saurabh Gupta", "36.99", "Out of Stock", "PaperBack"),
("SQL-Datenbanken", "Alfred Moos", "42.99", "Out of Stock", "PaperBack"),
("Beginning SQL Server 2005 Express", "Rick Dobson", "31.49", "Out of Stock", "PaperBack"),
("Practical Guide to Using SQL in Oracle", "Dr. Richard Earp", "46.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Business Intelligence Development and Maintenance", "Erik Veerman", "43.99", "Out of Stock", "PaperBack"),
("Professional Data Warehousing with SQL Server 7.0 and OLAP Services", "Sakhr Youness", "36.99", "Out of Stock", "PaperBack"),
("Professional SQL Server 2000 Data Warehousing with Analysis Services", "Chris Graves", "47.99", "Out of Stock", "PaperBack"),
("Professional Oracle PL/SQL Stored Procedures", "Wrox Author Team", "43.99", "Out of Stock", "PaperBack"),
("Pro VS 2005 Reporting Using SQL Server and Crystal Reports", "Rod Paddock", "51.45", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Implementation and Maintenance", "Mike Hotek", "43.99", "Out of Stock", "PaperBack"),
("Murachs SQL Server 2012 for Developers", "Bryan Syverson", "45.50", "Out of Stock", "PaperBack"),
("Designing SQL Server 2000 Databases", "Syngress Media", "33.99", "Out of Stock", "PaperBack"),
("Refactoring SQL Applications", "Stephane Faroult", "31.99", "Out of Stock", "PaperBack"),
("SQL Server 2008 Administration", "Rod Colledge", "28.99", "Out of Stock", "PaperBack"),
("The Microsoft Data Warehouse Toolkit", "Joy Mundy", "33.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005 Yukon Distilled", "Eric Brown", "25.99", "Out of Stock", "PaperBack"),
("The Guru's Guide to SQL Server Boxed Set", "Ken Henderson", "93.99", "Out of Stock", "PaperBack"),
("A Developer's Guide to SQL Server 2005", "Bob Beauchemin", "41.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Analysis Services Business Intelligence Skills for MCTS 70-448 and MCITP 70-452 Video Mentor", "Wendy Henry", "60.24", "Out of Stock", "PaperBack"),
("SQL Server 2000 Database Design and Implementation: MCAD/MCSD/MCSE Training Guide Exam 70-229", "Thomas Moore", "38.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Integration Services Business Intelligence Skills for MCTS 70-448 and MCITP 70-452 Video Mentor", "Wendy Henry", "60.24", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Reporting Services Business Intelligence Skills for MCTS 70-448 and MCITP 70-452 Video Mentor", "Wendy Henry", "60.24", "Out of Stock", "PaperBack"),
("SQL Server 2008 Database Administrator Portable Command Guide", "Darril Gibson", "23.99", "Out of Stock", "PaperBack"),
("SQL Server 2000 Replication Handbook", "David Winters", "21.99", "Out of Stock", "PaperBack"),
("Business Intelligence with SQL Server Reporting Services", "Adam Aspin", "29.50", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005 Administrator's Pocket Consultant", "William R. Stanek", "18.99", "Out of Stock", "PaperBack"),
("SQL for Microsoft Access", "C. Allison", "28.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Integration Services Problem-design-solution", "Erik Veerman", "33.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005 For Dummies", "Andrew Watt", "22.99", "Out of Stock", "PaperBack"),
("Inside Symbian SQL", "Ivan Litovski", "34.99", "Out of Stock", "PaperBack"),
("Beginning SQL Server 2005 Programming", "Robert Vieira", "25.99", "Out of Stock", "PaperBack"),
("Professional SQL Server 2005 Integration Services", "Brian Knight", "31.99", "Out of Stock", "PaperBack"),
("Delivering Business Intelligence with Microsoft SQL Server 2008 2008", "Brian Larson", "39.99", "Out of Stock", "PaperBack"),
("Hands-On Microsoft SQL Server 2008 Integration Services", "Ashwani Nanda", "47.99", "Out of Stock", "PaperBack"),
("Practical DMX Queries for Microsoft SQL Server Analysis Services 2008", "Arthur D. Tennick", "39.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 R2 Master Data Services", "Tyler Graham", "38.99", "Out of Stock", "PaperBack"),
("Practical MDX Queries", "Arthur D. Tennick", "36.99", "Out of Stock", "PaperBack"),
("Joe Celko's SQL Programming Style", "Joe Celko", "27.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2012 Master Data Services", "Tyler Graham", "38.99", "Out of Stock", "PaperBack"),
("Oracle Database 12C PL/SQL Advanced Programming Techniques", "Michael McLaughlin", "53.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005 Developer's Guide", "Michael Otey", "41.99", "Out of Stock", "PaperBack"),
("Hands-On Microsoft SQL Server 2005 Integration Services", "Ashwani Nanda", "40.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005 Reporting Services", "Brian Larson", "39.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005 Stored Procedure Programming in T-SQL and .NET", "Dejan Sunderic", "47.99", "Out of Stock", "PaperBack"),
("Delivering Business Intelligence with Microsoft SQL Server 2005", "Brian Larson", "32.99", "Out of Stock", "PaperBack"),
("Oracle Database 10g SQL", "Jason Price", "41.99", "Out of Stock", "PaperBack"),
("Expert Oracle PL/SQL", "Ron Hardman", "47.99", "Out of Stock", "PaperBack"),
("Oracle Database 11g PL/SQL Programming", "Michael McLaughlin", "47.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 High Availability with Clustering and Database Mirroring", "Michael Otey", "32.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008", "Dusan Petkovic", "32.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 New Features", "Michael Otey", "32.99", "Out of Stock", "PaperBack"),
("Joe Celko's Thinking in Sets", "Joe Celko", "20.99", "Out of Stock", "PaperBack"),
("Joe Celko's Data, Measurements and Standards in SQL", "Joe Celko", "33.99", "Out of Stock", "PaperBack"),
("Advanced Transact-SQL for SQL Server 2000", "Itzik Ben-Gan", "47.49", "Out of Stock", "PaperBack"),
("26 Dominios Con Ejercicios de SQL", "Tom S a P Rez Fern Ndez", "78.00", "Out of Stock", "PaperBack"),
("SQL Server 2012 with PowerShell V3 Cookbook", "Donabel Santos", "36.99", "Out of Stock", "PaperBack"),
("SQL Backup and Recovery Joes 2 Pros (R)", "Tim Radney", "4.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2012 Reporting Services", "Stacia Misner", "38.99", "Out of Stock", "PaperBack"),
("The Real MCTS SQL Server 2008 Exam 70-432 Prep Kit", "Mark Horninger", "38.99", "Out of Stock", "PaperBack"),
("Securing SQL Server", "Denny Cherry", "30.99", "Out of Stock", "PaperBack"),
("SQL Server Security Distilled", "Morris Lewis", "39.49", "Out of Stock", "PaperBack"),
("Essential SQL on SQL Server 2008", "Sikha Bagui", "34.99", "Out of Stock", "PaperBack"),
("Beginning Microsoft SQL Server 2008 Programming", "Robert Vieira", "26.99", "Out of Stock", "PaperBack"),
("The Nav/SQL Performance Field Guide", "Jrg Stryk", "23.90", "Out of Stock", "PaperBack"),
("SQL Server 2000 T-SQL Handbook", "Wrox Author Team", "36.99", "Out of Stock", "PaperBack"),
("OCP Developer PL/SQL Program Units Exam Guide", "Jason Couchman", "38.59", "Out of Stock", "PaperBack"),
("Learning SQL Server Reporting Services 2012", "Jayaram Krishnaswamy", "33.99", "Out of Stock", "PaperBack"),
("Data Warehousing with Ms Sql", "Poolet", "66.10", "Out of Stock", "PaperBack"),
("Learn SQL Server Administration in a Month of Lunches", "Don Jones", "21.99", "Out of Stock", "PaperBack"),
("SQL Server Internals", "Kalen Delaney", "19.99", "Out of Stock", "PaperBack"),
("SQL Deep Dives: v. 2", "Kalen Delaney", "38.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Administration with Windows PowerShell", "Ananthakumar Muthusamy", "39.99", "Out of Stock", "PaperBack"),
("Programming SQL Server 2005", "Shawn Wildermuth", "39.50", "Out of Stock", "PaperBack"),
("The Art of SQL", "Stephane Faroult", "31.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2000 Performance Tuning Technical Reference", "Microsoft Corporation", "30.99", "Out of Stock", "PaperBack"),
("Administrator's Guide to SQL Server 2005", "Buck Woody", "34.99", "Out of Stock", "PaperBack"),
("SQL Server Forensic Analysis", "Kevvie Fowler", "34.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 MDX Step by Step", "Bryan Smith", "30.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Analysis Service Step by Step", "Scott Cameron", "30.99", "Out of Stock", "PaperBack"),
("MCITP SQL Server 2005 Database Developer All-in-one Exam Guide", "Darril Gibson", "48.93", "Out of Stock", "PaperBack"),
("SQL Server 2000", "Jeffrey Shapiro", "36.99", "Out of Stock", "PaperBack"),
("Introducing Microsoft SQL Server 2012", "Ross Mistry", "8.99", "Out of Stock", "PaperBack"),
("SQL Injection Attacks and Defense", "Justin Clarke", "36.99", "Out of Stock", "PaperBack"),
("SQL Programming", "MCCALLISTER", "33.99", "Out of Stock", "PaperBack"),
("Advanced Standard SQL Dynamic Structured Data Modeling and Hierarchical Processing", "Michael M. David", "97.00", "Out of Stock", "PaperBack"),
("Using SQL Server 6.5 Special Edition", "Stephen Wynkoop", "55.52", "Out of Stock", "PaperBack"),
("The Language of SQL", "Larry Rockoff", "10.99", "Out of Stock", "PaperBack"),
("SQL Power!", "Kenneth Hess", "44.99", "Out of Stock", "PaperBack"),
("Database Design and Programming: With Access, SQL, Visual Basica and ASP", "John Carter", "50.99", "Out of Stock", "PaperBack"),
("Building Performance Dashboards and Balanced Scorecards with SQL Server Reporting Services", "Christopher Price", "33.99", "Out of Stock", "PaperBack"),
("Discovering SQL", "Alex Kriegel", "23.99", "Out of Stock", "PaperBack"),
("Professional Microsoft SQL Server 2012 Analysis Services with MDX and DAX", "Sivakumar Harinath", "36.99", "Out of Stock", "PaperBack"),
("Professional Microsoft SQL Server 2012 Reporting Services", "Paul Turley", "33.99", "Out of Stock", "PaperBack"),
("Professional SQL Server 2012 Internals and Troubleshooting", "Christian Bolton", "39.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2012 Administration", "Carpenter", "47.50", "Out of Stock", "PaperBack"),
("Professional Software Modeling with M and SQL Server Modeling", "Bill Sempf", "26.99", "Out of Stock", "PaperBack"),
("Oracle PL/SQL by Example", "Benjamin Rosenzweig", "43.99", "Out of Stock", "PaperBack"),
("Securing SQL Server", "Denny Cherry", "30.99", "Out of Stock", "PaperBack"),
("The Guru's Guide to SQL Server Stored Procedures", "Ken Henderson", "43.99", "Out of Stock", "PaperBack"),
("Transact-SQL Desk Reference", "Deac Lancaster", "27.99", "Out of Stock", "PaperBack"),
("SQL Performance Tuning", "Peter Gulutzan", "36.99", "Out of Stock", "PaperBack"),
("SQL for MySQL Developers", "Rick F. van der Lans", "36.99", "Out of Stock", "PaperBack"),
("Oracle PL/SQL by Example", "Benjamin Rosenzweig", "36.99", "Out of Stock", "PaperBack"),
("Oracle SQL", "Gavin Powell", "53.99", "Out of Stock", "PaperBack"),
("Course Ilt", "", "35.99", "Out of Stock", "PaperBack"),
("Ilt Sql Server 2000 Implement", "Course Technology", "89.99", "Out of Stock", "PaperBack"),
("SQL Server 2014", "Sikha Bagui", "141.99", "Out of Stock", "PaperBack"),
("SQL: 1999", "Jim Melton", "60.99", "Out of Stock", "PaperBack"),
("Advanced SQL 1999", "Jim Melton", "55.99", "Out of Stock", "PaperBack"),
("Querying XML", "Jim Melton", "45.99", "Out of Stock", "PaperBack"),
("Understanding the New SQL", "Jim Melton", "49.99", "Out of Stock", "PaperBack"),
("Programming Microsoft SQL Server 2000 with XML", "", "30.99", "Out of Stock", "PaperBack"),
("Programming Microsoft SQL Server 2005", "Andrew J. Brust", "30.99", "Out of Stock", "PaperBack"),
("Designing Database Solutions by Using Microsoft SQL Server 2005", "", "36.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005 Implementation and Maintenance", "", "36.99", "Out of Stock", "PaperBack"),
("MCITP Self-paced Training Kit (Exams 70-431, 70-443, 70-444)", "Solid Quality Learning", "86.99", "Out of Stock", "PaperBack"),
("T-SQL Programming", "Itzik Ben-Gan", "36.99", "Out of Stock", "PaperBack"),
("T-SQL Querying", "Itzik Ben-Gan", "30.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Administrator's Pocket Consultant", "William R. Stanek", "27.99", "Out of Stock", "PaperBack"),
("Programming Microsoft SQL Server 2012", "Leonard G. Lobel", "36.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2012 High-Performance T-SQL Using Window Functions", "Itzik Ben-Gan", "22.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2000 Programming by Example", "Joe Webb", "36.99", "Out of Stock", "PaperBack"),
("Troubleshooting SQL Server - A Guide for the Accidental DBA", "Jonathan Kehayias", "19.99", "Out of Stock", "PaperBack"),
("Oracle PL/SQL Interview Questions, Answers, and Explanations", "Terry Sanchez", "20.00", "Out of Stock", "PaperBack"),
("My SQL/PHP Database Applications: WITH Active Server Bible", "Brad Bulger", "35.99", "Out of Stock", "PaperBack"),
("Oracle Database 10g Pl/SQL 101", "Christopher Allen", "34.99", "Out of Stock", "PaperBack"),
("Headstart SQL Server 2000", "Curlingstone Author Team", "36.99", "Out of Stock", "PaperBack"),
("Learn Microsoft Sql Server 2000", "Jose A. Ramalho", "43.50", "Out of Stock", "PaperBack"),
("Inside Microsoft SQL Server 2000", "Kalen Delaney", "47.49", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2000 Programming Step by Step", "Microsoft Corporation", "30.99", "Out of Stock", "PaperBack"),
("SQL Server 2000 High Availability: Planning v.1", "Microsoft Press", "12.49", "Out of Stock", "PaperBack"),
("SQL Server 2000 High Availability: Deployment v.2", "Microsoft Press", "12.49", "Out of Stock", "PaperBack"),
("My SQL and JSP Web Applications", "James Turner", "32.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005 Integration Services", "Trey Johnson", "42.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Integration Services Unleashed", "Kirk Haselden", "38.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Reporting Services Unleashed", "Michael Lisin", "36.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Analysis Services Unleashed", "Edward Melomed", "38.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2012 Management and Administration", "Shirmattie Seenarine", "30.99", "Out of Stock", "PaperBack"),
("The SQL Programming Language", "Kirk Scott", "22.99", "Out of Stock", "PaperBack"),
("Postgre SQL Server Programming", "Hannu Krosing", "30.99", "Out of Stock", "PaperBack"),
("SQL for Microsoft Access", "Cecelia  L. Allison", "46.99", "Out of Stock", "PaperBack"),
("SQL in Easy Steps", "Mike McGrath", "10.99", "Out of Stock", "PaperBack"),
("SQL Fur Dummies", "Allen G. Taylor", "18.99", "Out of Stock", "PaperBack"),
("Oracle PL/SQL For Dummies", "Paul Dorsey", "22.99", "Out of Stock", "PaperBack"),
("Oracle PL/SQL Language Pocket Reference", "Steven Feuerstein", "9.99", "Out of Stock", "PaperBack"),
("Oracle PL/ SQL Developer's Workbook", "Steven Feuerstein", "39.50", "Out of Stock", "PaperBack"),
("SQL Server 2012 Reporting Services Blueprints", "Marlon Ribunal", "30.99", "Out of Stock", "PaperBack"),
("Retrieving Transportation Information with Constraint SQL and Constraint Datalog", "Craig Wademan Schiller", "59.00", "Out of Stock", "PaperBack"),
("SQL Wait Stats Joes 2 Pros", "Pinal Dave", "6.49", "Out of Stock", "PaperBack"),
("MCSE System Administration for SQL Server 7 Exam Prep", "B. Tolbart", "42.10", "Out of Stock", "PaperBack"),
("Oracle 8 PL/SQL Exam Cram", "Margaret R. Ault", "20.99", "Out of Stock", "PaperBack"),
("Beginning SQL Server 2005 Administration", "Dan Wood", "26.99", "Out of Stock", "PaperBack"),
("MCITP Administrator", "Victor Isakov", "31.99", "Out of Stock", "PaperBack"),
("Schaum's Outline of Fundamentals of SQL Programming", "Ramon A. Mata-Toledo", "11.99", "Out of Stock", "PaperBack"),
("Professional Microsoft SQL Server Analysis Services 2008 with MDX", "Sivakumar Harinath", "33.99", "Out of Stock", "PaperBack"),
("Knight's 24-Hour Trainer", "Brian Knight", "33.99", "Out of Stock", "PaperBack"),
("Oracle Database Administration for Microsoft SQL Server DBAs", "Michelle Malcher", "38.99", "Out of Stock", "PaperBack"),
("Oracle Database 10g Pl/SQL Programming", "Scott Urman", "44.99", "Out of Stock", "PaperBack"),
("SQL Fur Dummies", "Allen G. Taylor", "16.99", "In Stock", "PaperBack"),
("SQL Architecture Basics Joes 2 Pros Volume 3 (International Edition)", "Rick Morelan", "19.99", "In Stock", "PaperBack"),
("SQL Programming Joes 2 Pros Volume 4 (International Edition)", "Rick Morelan", "19.99", "In Stock", "PaperBack"),
("SQL Interoperability Joes 2 Pros Volume 5 (International Edition)", "Rick Morelan", "19.99", "In Stock", "PaperBack"),
("Pro ASP.NET for SQL Server", "Brennan Stehling", "47.49", "In Stock", "PaperBack"),
("Oracle 9i Web Application Programming for PL/SQL Development", "Susan Boardman", "27.99", "In Stock", "PaperBack"),
("Oracle 9i", "Lannes Morris-Murphy", "73.99", "In Stock", "PaperBack"),
("SQL Fundamentals and Visio Essn Sys Analys", "John J. Patrick", "23.99", "In Stock", "PaperBack"),
("Microsoft SQL Server 2005 Analysis Services", "Irina Gorbach", "42.99", "In Stock", "PaperBack"),
("Microsoft SQL Server 2005", "Trent Swanson", "42.99", "In Stock", "PaperBack"),
("Microsoft SQL Server 2005 Reporting Services", "Michael Lisin", "35.99", "In Stock", "PaperBack"),
("Microsoft SQL Server 2000 Notification Services", "Shyam Pather", "36.59", "In Stock", "PaperBack"),
("SQL Fundamentals LiveLessons (Video Training)", "Arie D. Jones", "97.02", "In Stock", "PaperBack"),
("Microsoft SQL Server 2005 Replication", "Philip Vaughn", "36.99", "In Stock", "PaperBack"),
("Microsoft SQL Server 2005 Notification Services", "Shyam Pather", "42.99", "In Stock", "PaperBack"),
("Microsoft Sams Teach Yourself SQL Server 2005 Express in 24 Hours", "Alison Balter", "24.99", "In Stock", "PaperBack"),
("Oracle Database 11g R2", "Sideris Courseware Corp", "76.00", "In Stock", "PaperBack"),
("Oracle Database 11g R2", "Sideris Courseware Corp", "50.00", "In Stock", "PaperBack"),
("Oracle Database 11g R2", "Sideris Courseware Corp", "50.00", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2012 with Hadoop", "Debarchan Sarkar", "24.99", "Out of Stock", "PaperBack"),
("SQL Server Tacklebox", "Rodney Landrum", "19.99", "Out of Stock", "PaperBack"),
("Guide to Sql", "Richard H Baker", "18.95", "Out of Stock", "PaperBack"),
("SQL Server 2005 DBA Street Smarts", "Joseph L. Jorden", "19.99", "Out of Stock", "PaperBack"),
("Professional SQL Server 2005 Performance Tuning", "Steven Wort", "33.99", "Out of Stock", "PaperBack"),
("70-432", "Microsoft Official Academic Course", "37.99", "Out of Stock", "PaperBack"),
("70-443 and 70-450", "Microsoft Official Academic Course", "37.99", "Out of Stock", "PaperBack"),
("SQL Bible", "Alex Kriegel", "42.50", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Bible", "Paul Nielsen", "39.99", "Out of Stock", "PaperBack"),
("Professional Microsoft SQL Server 2008 Administration", "Brian Knight", "45.00", "Out of Stock", "PaperBack"),
("Mastering SQL Server 2008", "Michael Lee", "39.99", "Out of Stock", "PaperBack"),
("Defensive Database Programming with SQL Server", "Alex Kuznetsov", "19.99", "Out of Stock", "PaperBack"),
("SQL Server Team Development", "Grant Fritchey", "29.99", "Out of Stock", "PaperBack"),
("Pro T-SQL 2008 Programmer's Guide", "Michael Coles", "41.99", "Out of Stock", "PaperBack"),
("Expert SQL Server 2008 Encryption", "Rodney Landrum", "39.50", "Out of Stock", "PaperBack"),
("Pro SQL Server 2012 BI Solutions", "Randal Root", "39.50", "Out of Stock", "PaperBack"),
("Beginning SQL Server 2012 for Developers", "Robin Dewson", "39.50", "Out of Stock", "PaperBack"),
("Pro SQL Server 2012 Administration 2012", "Ken Simmons", "47.50", "Out of Stock", "PaperBack"),
("MCTS Self-paced Training Kit and Online Course Bundle (exam 70-433): Microsoft SQL Server 2008 - Database Development Book/DVD Package", "Tobias Thernstrom", "54.99", "Out of Stock", "PaperBack"),
("26 Domeinu SQL Ariketekin", "Arantza Irastorza Go I", "79.00", "Out of Stock", "PaperBack"),
("SQL Basics Joes 2 Pros", "Rick Morelan", "6.99", "Out of Stock", "PaperBack"),
("Joe Celko's SQL for Smarties", "Joe Celko", "39.99", "Out of Stock", "PaperBack"),
("Accelerated SQL Server 2008 2008", "Rob Walters", "41.99", "Out of Stock", "PaperBack"),
("Inside the SQL Server Query Optimizer", "Benjamin Nevarez", "19.99", "Out of Stock", "PaperBack"),
("Razrabotka I Issledovanie Programmnoy Sistemy Translyatsii SQL-Zaprosov", "Tkachenko Kirill Stanislavovich", "51.00", "Out of Stock", "PaperBack"),
("Dissecting SQL Server Execution Plans", "Grant Fritchey", "19.99", "Out of Stock", "PaperBack"),
("A Guide to SQL", "Philip J. Pratt", "59.99", "Out of Stock", "PaperBack"),
("ASP.NET Programming with C# & SQL Server", "Don Gosselin", "59.99", "Out of Stock", "PaperBack"),
("OCP Introduction to Oracle9i", "Jason Couchman", "39.49", "Out of Stock", "PaperBack"),
("Joe Celko's SQL for Smarties", "Joe Celko", "41.99", "Out of Stock", "PaperBack"),
("SQL: A Beginner's Guide", "Andy Oppel", "24.99", "Out of Stock", "PaperBack"),
("Joe Celko's Trees and Hierarchies in SQL for Smarties", "Joe Celko", "27.99", "Out of Stock", "PaperBack"),
("Effective MySQL Optimizing SQL Statements", "Ronald Bradford", "28.99", "Out of Stock", "PaperBack"),
("Joe Celko's Complete Guide to NoSQL", "Joe Celko", "27.99", "Out of Stock", "PaperBack"),
("Oracle High-performance SQL Tuning", "Donald Keith Burleson", "36.99", "Out of Stock", "PaperBack"),
("Oracle Database 10g XML and SQL", "Mark Scardina", "52.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005", "Jeffrey Shapiro", "41.99", "Out of Stock", "PaperBack"),
("Joe Celko's SQL Puzzles and Answers", "Joe Celko", "40.99", "Out of Stock", "PaperBack"),
("SQL Demystified", "Andy Oppel", "16.99", "Out of Stock", "PaperBack"),
("Oracle SQL Developer Handbook", "Dan Hotka", "25.99", "Out of Stock", "PaperBack"),
("Oracle Database X PL/SQL Programming Workbook", "Michael McLaughlin", "41.99", "Out of Stock", "PaperBack"),
("Exam 70-461 Querying Microsoft SQL Server 2012 Lab Manual", "Microsoft Official Academic Course", "34.99", "Out of Stock", "PaperBack"),
("Exam 70-462 Administering Microsoft SQL Server 2012 Databases Lab Manual", "Microsoft Official Academic Course", "34.99", "Out of Stock", "PaperBack"),
("A Visual Introduction to SQL", "David Chappell", "57.50", "Out of Stock", "PaperBack"),
("Building a Data Warehouse", "Vincent Rainardi", "55.45", "Out of Stock", "PaperBack"),
("Pro SQL Server 2008 Failover Clustering", "Allan Hirt", "39.50", "Out of Stock", "PaperBack"),
("Pro SQL Server 2012 Integration Services", "Francis Rodrigues", "39.50", "Out of Stock", "PaperBack"),
("Beginning SQL Server 2012 Administration", "Robert Walters", "39.50", "Out of Stock", "PaperBack"),
("Building a Data Warehouse: with Examples in SQL Server", "Vincent Rainardi", "51.45", "Out of Stock", "PaperBack"),
("Oracle SQL Tuning with Oracle SQLTXPLAIN", "Stelios N. Charalambides", "26.50", "Out of Stock", "PaperBack"),
("Expert Oracle SQL", "Tony Hasler", "38.50", "Out of Stock", "PaperBack"),
("Murach's Oracle SQL and PL/SQL", "Joel Murach", "43.99", "Out of Stock", "PaperBack"),
("Implementing Data Mining Algorithms in Microsoft SQL Server", "C.L. Curotto", "114.00", "Out of Stock", "PaperBack"),
("Oracle 11g", "Joan Casteel", "37.99", "Out of Stock", "PaperBack"),
("Oracle 10g: SQL", "Joan Casteel", "78.99", "Out of Stock", "PaperBack"),
("70-228 MCSE Guide to MS SQL Server 2000 Administration", "Mathew Raftree", "80.99", "Out of Stock", "PaperBack"),
("Pro SQL Server 2008 Service Broker", "Klaus Aschenbrenner", "47.39", "Out of Stock", "PaperBack"),
("Pro SQL Database for Windows Azure: SQL Server in the Cloud", "Scott Klein", "39.50", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005", "Burzin Patel", "36.99", "Out of Stock", "PaperBack"),
("Real-world SQL-DMO for SQL Server", "Allen Mitchell", "39.49", "Out of Stock", "PaperBack"),
("Microsoft Sql Server 2000", "Prima Development", "44.50", "Out of Stock", "PaperBack"),
("SQL Server Hardware", "Glenn Berry", "19.99", "Out of Stock", "PaperBack"),
("SQL-Anfragen", "Gunter V. Bultzingsloewen", "42.99", "Out of Stock", "PaperBack"),
("Microsoft Sql Resource Guide", "TechRepublic", "55.50", "Out of Stock", "PaperBack"),
("Fast Track: Microsoft Sql Server 7.0/2000", "TechRepublic", "43.00", "Out of Stock", "PaperBack"),
("Database Language SQL Explained", "Central Computer & Telecommunications Agency", "30.00", "Out of Stock", "PaperBack"),
("MCSE SQL Server 7 Administration For Dummies", "Rozanne Whalen", "27.99", "Out of Stock", "PaperBack"),
("Using Excel VBA and Microsoft SQL Server as Reporting Enhancement", "Gita Renata Rustandi", "42.00", "Out of Stock", "PaperBack"),
("PostgreSQL 9.0 Reference Manual: The SQL Language 1A", "PostgreSQL Development Group", "14.95", "Out of Stock", "PaperBack"),
("SQL Server MVP Deep Dives in Action", "Paul Nielsen", "38.99", "Out of Stock", "PaperBack"),
("MCSE TestPrep: SQL Server 6.5", "Sean Baird", "36.95", "Out of Stock", "PaperBack"),
("Select Sql", "Lawrence R. Newcomer", "30.95", "Out of Stock", "PaperBack"),
("MCITP Administrator", "David W. Tschanz", "31.99", "Out of Stock", "PaperBack"),
("Oracle Pl/SQL", "Lakshman Bulusu", "35.99", "Out of Stock", "PaperBack"),
("Oracle SQL*Loader", "Jonathan Gennick", "28.50", "Out of Stock", "PaperBack"),
("How to Cheat at Securing SQL Server 2005", "Mark Horninger", "33.99", "Out of Stock", "PaperBack"),
("The Real MCTS SQL Server 2008 Exam 70-433 Prep Kit", "Mark Horninger", "38.99", "Out of Stock", "PaperBack"),
("Introduction to SQL and PL/SQL", "Sharad Maheshwari", "13.99", "Out of Stock", "PaperBack"),
("SQL Server 2012 Alwayson Joes 2 Pros (R)", "Vinod Kumar", "39.99", "Out of Stock", "PaperBack"),
("Keeping Ahead", "Joelle Mosset", "9.99", "Out of Stock", "PaperBack"),
("MCSE-administering SQL Server 7.0", "Jerome Gabillaud", "14.99", "Out of Stock", "PaperBack"),
("SQL Queries 2012 Joes 2 Pros (R) Volume 3", "Rick Morelan", "24.79", "Out of Stock", "PaperBack"),
("SQL Server Analysis Services 2012 Cube Development Cookbook", "Baya Dewald", "37.99", "Out of Stock", "PaperBack"),
("Oracle Database 11g SQL", "Jason Price", "41.99", "Out of Stock", "PaperBack"),
("OCA Oracle Database 11g SQL Fundamentals I Exam Guide: Exam 1Z0-051", "John Watson", "48.93", "Out of Stock", "PaperBack"),
("Oracle PL/SQL Performance Tuning Tips & Techniques", "Michael Rosenblum", "43.99", "Out of Stock", "PaperBack"),
("Learning Oracle PL/SQL", "Bill Pribyl", "35.50", "Out of Stock", "PaperBack"),
("SQL and Relational Theory", "C. J. Date", "26.50", "Out of Stock", "PaperBack"),
("Transact-SQL Cookbook", "Ales Spetic", "28.50", "Out of Stock", "PaperBack"),
("Getting Started with SQL Server 2012 Cube Development", "Simon Lidberg", "30.99", "Out of Stock", "PaperBack"),
("Beginners Guide to SQL Server Integration Services Using Visual Studio 2005", "Jayaram Krishnaswamy", "24.99", "Out of Stock", "PaperBack"),
("Oracle 9i", "Lannes Morris-Murphy", "41.99", "Out of Stock", "PaperBack"),
("MCSA Guide to Microsoft SQL Server 2012 (Exam 70-462)", "Faisal Akkawi", "43.99", "Out of Stock", "PaperBack"),
("SQL- A Simple Introduction by Cliff", "Cliff Beacham", "22.95", "Out of Stock", "PaperBack"),
("Expert SQL Server Performance Engineering", "Thomas Grohser", "47.49", "Out of Stock", "PaperBack"),
("Mastering SQL Server 7.0", "D. P. Nagpal", "10.95", "Out of Stock", "PaperBack"),
("Advanced ANSI SQL Data Modeling and Structure Processing", "Michael M. David", "27.00", "Out of Stock", "PaperBack"),
("MCSA in Depth", "Faisal Akkawi", "31.99", "Out of Stock", "PaperBack"),
("MCSA MS SQL Server 2012 DB Q&A 70-462", "Chimborazo Publishing Inc.", "15.99", "Out of Stock", "PaperBack"),
("Mapping of a Natural Language Query to SQL for English/Urdu", "Rashid Ahmad", "42.00", "Out of Stock", "PaperBack"),
("Fundamentals of SQL Server 2012 Replication", "Sebastian Meine", "19.99", "Out of Stock", "PaperBack"),
("Professional Microsoft SQL Server 2008 Integration Services", "Brian Knight", "33.99", "Out of Stock", "PaperBack"),
("Fundamentals of Database Management Systems: WITH Beginning SQL Server 2005 Programming", "Mark L. Gillenson", "58.95", "Out of Stock", "PaperBack"),
("SQL Queries 2012 Joes 2 Pros (R) Volume 5", "Rick Morelan", "24.79", "Out of Stock", "PaperBack"),
("SQL Server Security", "Chip Andrews", "41.99", "Out of Stock", "PaperBack"),
("Tribal SQL", "Various", "19.99", "Out of Stock", "PaperBack"),
("Instant Microsoft SQL Server Analysis Services 2012 Dimensions and Cube", "Anurag Acharya", "13.99", "Out of Stock", "PaperBack"),
("Professional Microsoft SQL Server 2008 Programming", "Robert Vieira", "33.99", "Out of Stock", "PaperBack"),
("Data Mining with Microsoft SQL Server 2008", "Jamie MacLennan", "33.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 7 For Dummies", "Anthony Mann", "28.99", "Out of Stock", "PaperBack"),
("SQL Server 2005 Bible", "Paul Nielsen", "31.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005 Reporting Services For Dummies", "Mark Robinson", "21.99", "Out of Stock", "PaperBack"),
("MDX Solutions", "George Spofford", "47.50", "Out of Stock", "PaperBack"),
("Beginning Microsoft SQL Server 2008 Administration", "Chris Leiter", "33.99", "Out of Stock", "PaperBack"),
("SQL Interactivo", "Ismael Esquivel G Mez", "34.00", "Out of Stock", "PaperBack"),
("Beginning SQL Joes 2 Pros (International Edition)", "Rick A. Morelan", "10.99", "Out of Stock", "PaperBack"),
("SQL Queries Joes 2 Pros Volume 2 (International Edition)", "Rick Morelan", "17.99", "Out of Stock", "PaperBack"),
("70-431", "Microsoft Official Academic Course", "59.95", "Out of Stock", "PaperBack"),
("70-431", "Microsoft", "36.99", "Out of Stock", "PaperBack"),
("Hitchhiker Visual Basic and Sql", "", "46.99", "Out of Stock", "PaperBack"),
("SQL Server Interview Questions and Answers", "Pinal Dave", "6.99", "Out of Stock", "PaperBack"),
("Studyguide for SQL Fundamentals by Patrick, John J., ISBN 9780137126026", "Cram101 Textbook Reviews", "21.99", "Out of Stock", "PaperBack"),
("SAS 9.3 SQL Procedure User's Guide", "SAS Publishing", "27.23", "Out of Stock", "PaperBack"),
("The Microsoft SQL Server 2000 Performance Optimization and Tuning Handbook", "Ken England", "50.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005 Performance Optimization and Tuning Handbook", "Ken England", "44.99", "Out of Stock", "PaperBack"),
("Oracle PL/SQL For Dummies", "Michael Rosenblum", "24.99", "Out of Stock", "PaperBack"),
("SQL Server CE Database Development with the .Net Compact Framework", "Rob Tiffany", "39.49", "Out of Stock", "PaperBack"),
("Real World SQL Server Administration with Perl", "Dave Shea", "47.49", "Out of Stock", "PaperBack"),
("The Programmer's Guide to SQL", "Cristian Darie", "35.49", "Out of Stock", "PaperBack"),
("Mastering Oracle PL/SQL", "Katz Chaim", "39.49", "Out of Stock", "PaperBack"),
("Mastering Oracle SQL and SQL Plus", "Lex DeHaan", "31.49", "Out of Stock", "PaperBack"),
("Pro SQL Server 2005 Database Design and Optimization", "Kevin Kline", "47.49", "Out of Stock", "PaperBack"),
("Expert SQL Server 2005 Development", "Adam Machanic", "39.49", "Out of Stock", "PaperBack"),
("Beginning PL/SQL", "Donald Bales", "35.49", "Out of Stock", "PaperBack"),
("Pro SQL Server 2008 Reporting Services", "Rodney Landrum", "31.49", "Out of Stock", "PaperBack"),
("Beginning SQL Server for Developers 2015", "Robin Dewson", "29.50", "Out of Stock", "PaperBack"),
("Mastering SQL Server 2014 Data Mining", "Amarpreet Singh Bassan", "30.99", "Out of Stock", "PaperBack"),
("Professional SQL Server 2005 Programming", "Robert Vieira", "31.99", "Out of Stock", "PaperBack"),
("Professional SQL Server 2005 Reporting Services", "Paul Turley", "25.99", "Out of Stock", "PaperBack"),
("Professional SQL Server 2005 XML", "Scott Klein", "31.99", "Out of Stock", "PaperBack"),
("Using SQL", "Rafe Colburn", "28.99", "Out of Stock", "PaperBack"),
("MCITP Developer", "Victor Isakov", "39.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Database Development", "Tobias Thernstrom", "43.99", "Out of Stock", "PaperBack"),
("Pro SQL Server 2008 Mirroring", "Ken Simmons", "43.50", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2012 Integration Services: An Expert Cookbook", "Reza Rad", "27.99", "Out of Stock", "PaperBack"),
("Beginning Transact-SQL with SQL Server 2000 and 2005", "Paul Turley", "25.99", "Out of Stock", "PaperBack"),
("The Storage Engine", "Kalen Delaney", "30.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005 Reporting Services Step by Step", "Stacia Misner", "27.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005 Analysis Services Step by Step", "Reed Jacobson", "24.99", "Out of Stock", "PaperBack"),
("Getting Started with Impala", "John Russell", "21.50", "Out of Stock", "PaperBack"),
("SQL Tuning", "Dan Tow", "28.50", "Out of Stock", "PaperBack"),
("Oracle PL/SQL Best Practices", "Steven Feuerstein", "21.50", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2012 Security Cookbook", "Rudi Bruchez", "30.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Reporting Services", "Brian Larson", "39.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 For Dummies", "Mike Chapple", "22.99", "Out of Stock", "PaperBack"),
("Securing SQL Server", "Denny Cherry", "36.99", "Out of Stock", "PaperBack"),
("Oracle SQL Tuning Pocket Reference", "Mark Gurry", "6.99", "Out of Stock", "PaperBack"),
("Oracle PL/SQL Programming", "Steven Feuerstein", "53.99", "Out of Stock", "PaperBack"),
("Oracle PL/SQL in 10 Minutes, Sams Teach Yourself", "Ben Forta", "18.99", "Out of Stock", "PaperBack"),
("Oracle Database 12c SQL", "Jason Price", "46.99", "Out of Stock", "PaperBack"),
("Proc SQL", "Kirk P Lafler", "35.37", "Out of Stock", "PaperBack"),
("Beginning T-SQL with Microsoft SQL Server 2005 and 2008", "Paul Turley", "26.99", "Out of Stock", "PaperBack"),
("Hitchhiker's Guide to SQL Server 2000 Reporting Services", "Peter Blackburn", "34.99", "Out of Stock", "PaperBack"),
("A Guide to SQL", "Philip J. Pratt", "36.99", "Out of Stock", "PaperBack"),
("Mining Mountains of Data: Organizing All Atom Molecular Dynamics Protein Simulation Data Into SQL and OLAP Cubes", "Brittney D Jung-Hynes", "59.00", "Out of Stock", "PaperBack"),
("Pro SQL Server 2012 Extended Events", "Jason Strate", "32.50", "Out of Stock", "PaperBack"),
("SQL Server 2008 Query Performance Tuning Distilled", "Grant Fritchey", "43.49", "Out of Stock", "PaperBack"),
("Beginning T-SQL 2008", "Kathi Kellenberger", "31.49", "Out of Stock", "PaperBack"),
("Pro SQL Server 2008 Analytics", "B. Paulen", "39.50", "Out of Stock", "PaperBack"),
("Pro SQL Server 2008 Relational Database Design and Implementation", "Louis Davidson", "39.50", "Out of Stock", "PaperBack"),
("Beginning T-SQL 2012", "Scott Shaw", "39.50", "Out of Stock", "PaperBack"),
("Expert Performance Indexing for SQL Server 2012", "Jason Strate", "39.50", "Out of Stock", "PaperBack"),
("Pro SQL Server 2012 Reporting Services", "Brian McDonald", "39.50", "Out of Stock", "PaperBack"),
("Beginning SQL Server Modeling", "Bart Weller", "39.50", "Out of Stock", "PaperBack"),
("SQL Server 2012 Administration Joes 2 Pros (R) Volume 1", "Rick Morelan", "12.99", "Out of Stock", "PaperBack"),
("The Art of XSD - SQL Server XML Schemas", "Jacob Sebastian", "19.99", "Out of Stock", "PaperBack"),
("SQL Server Transaction Log Management", "Tony Davis", "19.99", "Out of Stock", "PaperBack"),
("SQL Queries 2012 Joes 2 Pros (R) Volume 2", "Rick Morelan", "20.99", "Out of Stock", "PaperBack"),
("Mitigar Inyecciones SQL Con Tecnicas de Mineria de Datos", "Rogfel Thompson Mart Nez", "24.00", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2012 a Beginners Guide", "Dusan Petkovic", "30.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2005", "Duscan Petkovic", "30.99", "Out of Stock", "PaperBack"),
("MCDBA SQL Server 2005: Exam 70-431", "Chris McCain", "35.56", "Out of Stock", "PaperBack"),
("SQL Anywhere Studio 9 Developer's Guide", "Jose A. Ramalho", "60.99", "Out of Stock", "PaperBack"),
("PROC SQL by Example", "Howard Schreier", "31.67", "Out of Stock", "PaperBack"),
("Beginning SQL", "Paul Wilton", "24.99", "Out of Stock", "PaperBack"),
("T-SQL Programming", "Itzik Ben-Gan", "27.99", "Out of Stock", "PaperBack"),
("Query Tuning and Optimization", "Kalen Delaney", "30.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Internals", "Kalen Delaney", "36.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2012 Internals", "Kalen Delaney", "38.99", "Out of Stock", "PaperBack"),
("Microsoft Azure SQL Database Step by Step", "Leonard G. Lobel", "24.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2012 Integration Services", "Wee-Hyong Tok", "36.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2012 Pocket Consultant", "William R. Stanek", "24.99", "Out of Stock", "PaperBack"),
("SQL Server 2005 Reporting Services in Action", "Teo Lachev", "35.99", "Out of Stock", "PaperBack"),
("Defensive Database Programming with SQL Server", "Alex Kuznetsov", "19.99", "Out of Stock", "PaperBack"),
("Oracle SQL Developer 2.1", "Sue Harper", "33.99", "Out of Stock", "PaperBack"),
("Pro T-SQL Programmer's Guide 2015", "Jay Natarajan", "35.50", "Out of Stock", "PaperBack"),
("Murachs Oracle SQL & Pl / SQL for Developers", "Joel Murach", "45.50", "Out of Stock", "PaperBack"),
("Professional Microsoft SQL Server 2012 Integration Services", "Brian Knight", "33.99", "Out of Stock", "PaperBack"),
("Time and Relational Theory", "C. J. Date", "36.99", "Out of Stock", "PaperBack"),
("Problem Solving for Mdx for SQL Server 2005 2005", "Mark Whitehorn", "39.50", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 R2 Master Data Services", "Jeremy Kashel", "33.99", "Out of Stock", "PaperBack"),
("Learning SQL Server 2008 Reporting Services", "Jayaram Krishnaswamy", "30.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 7 Administrator's Guide", "R. Talmage", "70.88", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2000 Administrator's Pocket Consultant", "Microsoft Corporation", "18.99", "Out of Stock", "PaperBack"),
("SQL Server Yukon Version", "David M. Kroenke", "14.29", "Out of Stock", "PaperBack"),
("Professional Microsoft SQL Server 2012 Administration", "Adam Jorgensen", "33.99", "Out of Stock", "PaperBack"),
("Als Microsoft Sql Server 2000 System Administration", "Microsoft Press", "36.99", "Out of Stock", "PaperBack"),
("Microsoft Access Projects with Microsoft Sql Server", "Ralf Albrecht", "36.99", "Out of Stock", "PaperBack"),
("Professional Microsoft PowerPivot for Excel and SharePoint", "Sivakumar Harinath", "29.99", "Out of Stock", "PaperBack"),
("SQL Clearly Explained", "Jan L. Harrington", "36.99", "Out of Stock", "PaperBack"),
("Reporting with Microsoft SQL Server 2012", "James Serra", "21.99", "Out of Stock", "PaperBack"),
("Oracle JDeveloper for Forms and PL/SQL Developers: A Guide to Web Development with Oracle ADF", "Peter Koletzke", "38.99", "Out of Stock", "PaperBack"),
("Business Intelligence Automatisierung Durch Data Vault", "Christian Garbsch", "39.99", "Out of Stock", "PaperBack"),
("MDX with Microsoft SQL Server 2008 R2 Analysis Services Cookbook", "Tomislav Piasevoli", "30.99", "Out of Stock", "PaperBack"),
("SQL Aplicado a la Empresa", "Sergio Adri Martin", "24.00", "Out of Stock", "PaperBack"),
("SQL Server 2014 Development Essentials", "Basit A. Masood-Al-Farooq", "27.99", "Out of Stock", "PaperBack"),
("PostgreSQL 9.0 Reference Manual: SQL Command Reference 1B", "PostgreSQL Development Group", "14.95", "Out of Stock", "PaperBack"),
("Brad's Sure Guide to SQL Server Maintenance Plans", "Brad M. McGehee", "19.99", "Out of Stock", "PaperBack"),
("Introducing Microsoft SQL Server 2014", "Ross Mistry", "5.99", "Out of Stock", "PaperBack"),
("Beginning Oracle SQL", "Lex DeHaan", "35.43", "Out of Stock", "PaperBack"),
("Pro T-SQL 2005 Programmer's Guide", "Michael Coles", "39.49", "Out of Stock", "PaperBack"),
("Advanced SQL Functions in Oracle 10G", "Dr. Richard Earp", "7.50", "Out of Stock", "PaperBack"),
("SQL, PL/SQL the Programming Language of Oracle", "Ivan Bayross", "12.00", "Out of Stock", "PaperBack"),
("Teach Yourself SQL and PL/SQL Using Oracle 8i and 9i", "Ivan Bayross", "13.50", "Out of Stock", "PaperBack"),
("Teach Yourself SQL/PL SQL Using Oracle 8i and 9i with SQLJ", "Ivan Bayross", "4.50", "Out of Stock", "PaperBack"),
("A Guide to SQL", "Philip J. Pratt", "51.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Administrator's Pocket Consultant", "William R. Stanek", "21.99", "Out of Stock", "PaperBack"),
("SQL Server 2000 for Experienced DBAs", "Brian Knight", "36.99", "Out of Stock", "PaperBack"),
("SQL Server 2012 Administration Joes 2 Pros (R) Volume 2", "Rick Morelan", "17.99", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Administration for Oracle DBAs", "Mark Anderson", "38.99", "Out of Stock", "PaperBack"),
("SQL Server 2005", "", "14.29", "Out of Stock", "PaperBack"),
("SQL 2012 Queries for SQL 2008 Experts Joes 2 Pros (R)", "Rick Morelan", "30.98", "Out of Stock", "PaperBack"),
("Comecando Com SQL Joes 2 Pros", "Rick Morelan", "9.99", "Out of Stock", "PaperBack"),
("PostgreSQL 8.4 Official Documentation - Volume I. the SQL Language", "Postgresql Global Development Group The Postgresql Global Development Group", "23.99", "Out of Stock", "PaperBack"),
("The Essential PROC SQL Handbook for SAS Users", "Katherine Prairie", "53.86", "Out of Stock", "PaperBack"),
("SQL-Datenbanken Unter Unix", "Ralf Steffler", "28.90", "In Stock", "PaperBack"),
("SQL 2012 Functions Joes 2 Pros (R)", "Rick Morelan", "4.09", "In Stock", "PaperBack"),
("SQL Server DMVs in Action", "Ian W. Stirk", "41.99", "In Stock", "PaperBack"),
("SQL Server Integration Services Design Patterns 2014", "Tim Mitchell", "35.50", "In Stock", "PaperBack"),
("Pro SQL Server Administration 2015", "Peter Carter", "35.50", "In Stock", "PaperBack"),
("Beginning T-SQL 2014", "Kathi Kellenberger", "29.50", "In Stock", "PaperBack"),
("Extending SSIS with .NET Scripting 2015", "Joost Van Rossum", "29.50", "In Stock", "PaperBack"),
("Healthy SQL", "Robert Pearl", "32.50", "In Stock", "PaperBack"),
("Joe Celko's Data, Measurements and Standards in SQL", "Joe Celko", "45.65", "In Stock", "PaperBack"),
("Oracle&#174; PL/SQL&#0153; by Example", "Benjamin Rosenzweig", "48.26", "In Stock", "PaperBack"),
("Data Mining with Microsoft SQL Server 2008", "Jamie MacLennan", "43.10", "In Stock", "PaperBack"),
("Joe Celko's SQL for Smarties", "Joe Celko", "55.99", "In Stock", "PaperBack"),
("Microsoft SQL Server 2008 R2 Unleashed", "Ray Rankins", "41.38", "In Stock", "PaperBack"),
("Joe Celko's SQL for Smarties", "Joe Celko", "58.58", "In Stock", "PaperBack"),
("Joe Celko's Trees and Hierarchies in SQL for Smarties", "Joe Celko", "40.48", "In Stock", "PaperBack"),
("SQL and Relational Theory", "C.J. Date", "27.58", "In Stock", "PaperBack"),
("SQL Cookbook", "Anthony Molinaro", "27.58", "In Stock", "PaperBack"),
("Mastering Oracle SQL", "Sanjay Mishra", "27.58", "In Stock", "PaperBack"),
("Microsoft&#174; SQL Server&#8482; 2008 Reporting Services Unleashed", "Michael Lisin", "33.68", "In Stock", "eBook"),
("Professional SQL Server 2008 Internals and Troubleshooting", "Christian Bolton", "51.72", "In Stock", "eBook"),
("Joe Celko's SQL Programming Style", "Joe Celko", "37.88", "In Stock", "eBook"),
("Microsoft SQL Server 2008 Integration Services", "Erik Veerman", "43.09", "In Stock", "eBook"),
("SQL Pocket Guide", "Jonathan Gennick", "10.33", "In Stock", "eBook"),
("Oracle PL/SQL For Dummies", "Michael Rosenblum", "27.58", "In Stock", "eBook"),
("Sams Teach Yourself SQL in 10 Minutes", "Ben Forta", "17.23", "In Stock", "eBook"),
("Microsoft SQL Server 2005 Analysis Services", "Edward Melomed", "44.82", "In Stock", "eBook"),
("SQL Hacks", "Andrew Cumming", "20.68", "In Stock", "eBook"),
("SQL in a Nutshell", "Kevin Kline", "31.03", "In Stock", "eBook"),
("The Art of SQL", "Stephane Faroult", "31.03", "In Stock", "eBook"),
("Transact-SQL Cookbook", "Ales Spetic", "24.13", "In Stock", "eBook"),
("How to Cheat at Securing SQL Server 2005", "Mark Horninger", "44.78", "In Stock", "eBook"),
("SQL Server Forensic Analysis", "Kevvie Fowler", "37.92", "In Stock", "eBook"),
("Professional Microsoft SQL Server 2008 Integration Services", "Brian Knight", "43.09", "In Stock", "eBook"),
("Securing HP NonStop Servers in an Open Systems World", "Xypro Technology Corp", "113.80", "In Stock", "eBook"),
("Microsoft SQL Server Reporting Services Recipes", "Paul Turley", "43.09", "In Stock", "eBook"),
("MySQL Pocket Reference", "George Reese", "10.33", "In Stock", "eBook"),
("Oracle PL/SQL Best Practices", "Steven Feuerstein", "12.06", "In Stock", "eBook"),
("Oracle SQL*Plus", "Jonathan Gennick", "27.58", "In Stock", "eBook"),
("Programming SQL Server 2005", "Bill Hamilton", "37.92", "In Stock", "eBook"),
("Refactoring SQL Applications", "Stephane Faroult", "31.03", "In Stock", "eBook"),
("SQL Tuning", "Dan Tow", "27.58", "In Stock", "eBook"),
("The Real MCTS SQL Server 2008 Exam 70-433 Prep Kit", "Mark Horninger", "51.68", "In Stock", "eBook"),
("Securing SQL Server", "Denny Cherry", "43.06", "In Stock", "eBook"),
("Learning SQL", "Alan Beaulieu", "27.58", "In Stock", "eBook"),
("Sams Teach Yourself Microsoft&#174; SQL Server T-SQL in 10 Minutes", "Ben Forta", "20.68", "In Stock", "eBook"),
("Beginning T-SQL with Microsoft SQL Server 2005 and 2008", "Paul Turley", "34.48", "In Stock", "eBook"),
("Microsoft SQL ServerTM 2008 All-in-One Desk Reference For Dummies&#174;", "Robert D. Schneider", "34.48", "In Stock", "eBook"),
("Microsoft SQL Server 2008 For Dummies", "Mike Chapple", "27.58", "In Stock", "eBook"),
("Professional Microsoft SQL Server Analysis Services 2008 with MDX", "Sivakumar Harinath", "43.09", "In Stock", "eBook"),
("Querying XML", "Jim Melton", "62.03", "In Stock", "eBook"),
("Joe Celko's Trees and Hierarchies in SQL for Smarties", "Joe Celko", "38.75", "In Stock", "eBook"),
("Oracle PL/SQL Best Practices", "Steven Feuerstein", "20.68", "In Stock", "eBook"),
("SQL Pocket Guide", "Jonathan Gennick", "10.33", "In Stock", "eBook"),
("100 sposobów na SQL", "Andrew Cumming", "10.34", "In Stock", "eBook"),
("Learning SQL", "Alan Beaulieu", "24.13", "In Stock", "eBook"),
("Learning SQL on SQL Server 2005", "Sikha Saha Bagui", "31.03", "In Stock", "eBook"),
("Oracle PL/SQL Programming", "Steven Feuerstein", "44.82", "In Stock", "eBook"),
("Managing & Using MySQL", "Tim King", "27.58", "In Stock", "eBook"),
("Professional Microsoft SQL Server 2012 Integration Services", "Brian Knight", "43.09", "In Stock", "eBook"),
("Microsoft SQL Server 2005 Integration Services", "Kirk Haselden", "44.82", "In Stock", "eBook"),
("The Real MCTS SQL Server 2008 Exam 70-432 Prep Kit", "Mark Horninger", "51.68", "In Stock", "eBook"),
("SQL Server 2008 Administration", "Tom Carpenter", "64.66", "In Stock", "eBook"),
("Professional Microsoft SQL Server 2008 Programming", "Robert Vieira", "43.09", "In Stock", "eBook"),
("A Developer's Guide to SQL Server 2005", "Bob Beauchemin", "43.80", "In Stock", "eBook"),
("Sams Teach Yourself SQL in 24 Hours", "Ryan Stephens", "23.58", "In Stock", "eBook"),
("Data Analysis Using SQL and Excel", "Gordon S. Linoff", "38.80", "In Stock", "eBook"),
("Knight's 24-Hour Trainer", "Brian Knight", "43.09", "In Stock", "eBook"),
("SQL Built-In Functions and Stored Procedures", "Mike Faust", "43.09", "In Stock", "eBook"),
("Oracle PL/SQL Programming", "Steven Feuerstein", "37.92", "In Stock", "eBook"),
("Database Design and SQL for DB2", "James Cooper", "68.95", "In Stock", "eBook"),
("Microsoft SQL Server 2005", "Scalability Experts, Inc.", "24.13", "In Stock", "eBook"),
("Microsoft SQL Server 2005 Management and Administration", "Ross Mistry", "31.03", "In Stock", "eBook"),
("User Interface Design for Mere Mortals", "Eric Butow", "41.38", "In Stock", "eBook"),
("Professional Microsoft SQL Server 2012 Reporting Services", "Paul Turley", "43.09", "In Stock", "eBook"),
("SQL for eServer i5 and iSeries", "Kevin Forsythe", "55.99", "In Stock", "eBook"),
("Sams Teach Yourself SQL in 10 Minutes", "Ben Forta", "20.68", "In Stock", "eBook"),
("Knight's Microsoft SQL Server 2012 Integration Services  24-Hour Trainer", "Brian Knight", "43.09", "In Stock", "eBook"),
("Microsoft SQL Server 2012 Bible", "Adam Jorgensen", "51.72", "In Stock", "eBook"),
("Professional Microsoft SQL Server 2012 Administration", "Adam Jorgensen", "43.09", "In Stock", "eBook"),
("Oracle PL/SQL for DBAs", "Arup Nanda", "31.03", "In Stock", "eBook"),
("Oracle SQL Tuning Pocket Reference", "Mark Gurry", "6.89", "In Stock", "eBook"),
("SQL in a Nutshell", "Kevin Kline", "31.03", "In Stock", "eBook"),
("SQL All-in-One For Dummies", "Allen G. Taylor", "34.48", "In Stock", "eBook"),
("The Microsoft Data Warehouse Toolkit", "Joy Mundy", "42.12", "In Stock", "eBook"),
("Designing SQL Server 2000 Databases", "Syngress", "44.78", "In Stock", "eBook"),
("Microsoft SQL Server 2012 Administration", "Tom Carpenter", "60.34", "In Stock", "eBook"),
("Beginning Microsoft SQL Server 2012 Programming", "Paul Atkinson", "34.48", "In Stock", "eBook"),
("Virtualizing SQL Server with VMware", "Michael Corey", "31.03", "In Stock", "eBook"),
("Professional SQL Server 2012 Internals and Troubleshooting", "Christian Bolton", "51.72", "In Stock", "eBook"),
("Discovering SQL", "Alex Kriegel", "30.17", "In Stock", "eBook"),
("Sams Teach Yourself SQL in One Hour a Day", "Ryan Stephens", "37.92", "In Stock", "eBook"),
("Administrator's Guide to SQL Server 2005", "Buck Woody", "37.92", "In Stock", "eBook"),
("Sams Teach Yourself SQL in 24 Hours", "Ryan Stephens", "24.13", "In Stock", "eBook"),
("SQL for MySQL Developers", "Rick F. van der Lans", "37.92", "In Stock", "eBook"),
("SQL Queries for Mere Mortals", "John Viescas", "34.48", "In Stock", "eBook"),
("SQL Server 2005 Distilled", "Eric Brown", "27.58", "In Stock", "eBook"),
("DB2 SQL Tuning Tips for z/OS Developers", "Tony Andrews", "27.58", "In Stock", "eBook"),
("Microsoft SQL Server 2005 Notification Services", "Shyam Pather", "40.43", "In Stock", "eBook"),
("Microsoft SQL Server 2005 Reporting Services", "Michael Lisin", "37.92", "In Stock", "eBook"),
("SQL. Sztuka programowania", "Stephane Faroult", "12.07", "In Stock", "eBook"),
("Oracle PL/SQL Programming", "Steven Feuerstein", "48.26", "In Stock", "eBook"),
("SQL Injection Attacks and Defense", "Justin Clarke", "51.68", "In Stock", "eBook"),
("Microsoft SQL Server 2012 Internals", "Kalen Delaney", "43.09", "In Stock", "eBook"),
("Windows Azure SQL Database Step by Step", "Leonard G. Lobel", "27.58", "In Stock", "eBook"),
("SQL Injection Attacks and Defense", "Justin Clarke", "51.68", "In Stock", "eBook"),
("Securing SQL Server", "Denny Cherry", "43.06", "In Stock", "eBook"),
("Time and Relational Theory", "C.J. Date", "50.82", "In Stock", "eBook"),
("Microsoft SQL Server 2012 Unleashed", "Ray Rankins", "41.38", "In Stock", "eBook"),
("Getting Started with Impala", "John Russell", "22.40", "In Stock", "eBook"),
("Joe Celko's SQL for Smarties", "Joe Celko", "55.99", "In Stock", "eBook"),
("Joe Celko's Complete Guide to NoSQL", "Joe Celko", "38.75", "In Stock", "eBook"),
("A Developer's Guide to Data Modeling for SQL Server", "Eric Johnson", "34.48", "In Stock", "eBook"),
("Microsoft SQL Server 2008 Bible", "Paul Nielsen", "51.72", "In Stock", "eBook"),
("The Best Damn Exchange, SQL and IIS Book Period", "Henrik Walther", "54.26", "In Stock", "eBook"),
("Sams Teach Yourself SQL Server 2005 Express in 24 Hours", "Alison Balter", "24.13", "In Stock", "eBook"),
("SQL Clearly Explained", "Jan L. Harrington", "50.82", "In Stock", "eBook"),
("Professional Microsoft SQL Server 2012 Analysis Services with MDX and DAX", "Sivakumar Harinath", "47.40", "In Stock", "eBook"),
("SQL For Dummies", "Allen G. Taylor", "25.85", "In Stock", "eBook"),
("Oracle&#174; SQL by Example", "Alice Rischert", "48.26", "In Stock", "eBook"),
("The Complete Idiot's Guide to SQL", "Steven Holzner, Ph.D.", "17.20", "In Stock", "eBook"),
("SQL Server T-SQL Recipes 2015", "David Dye", "35.50", "In Stock", "eBook"),
("Moving Data 2016", "Martin Brown", "29.50", "In Stock", "eBook"),
("Beginning Oracle PL/SQL 2015", "Donald Bales", "26.50", "In Stock", "eBook"),
("Expert T-SQL Window Functions in SQL Server", "Kathi Kellenberger", "14.50", "In Stock", "eBook"),
("Datenbanken Und SQL", "Edwin Schicker", "25.99", "In Stock", "eBook"),
("Web Coding Bible (18 Books in 1 -- HTML, CSS, JavaScript, PHP, SQL, XML, Svg, Canvas, Webgl, Java Applet, ActionScript, Htaccess, Jquery, Wordpress, Seo and Many More)", "Chong Lip Phang", "25.00", "In Stock", "eBook"),
("Simply SQL", "Rudy Limeback", "25.00", "Out of Stock", "PaperBack"),
("T-SQL Querying", "Itzik Ben-Gan", "41.38", "Out of Stock", "PaperBack"),
("Oracle PL/SQL by Example", "Benjamin Rosenzweig", "40.43", "Out of Stock", "PaperBack"),
("PowerShell for SQL Server Essentials", "Donabel Santos", "11.99", "Out of Stock", "PaperBack"),
("Multilayered SQL Injection Prevention Mechanism", "Andodariya Vishal", "26.00", "Out of Stock", "PaperBack"),
("T-SQL in One Hour a Day, Sams Teach Yourself", "Alison Balter", "24.99", "Out of Stock", "PaperBack"),
("XML Integration Into an SQL-Based Cep Engine", "Prodanov Martin", "36.00", "Out of Stock", "PaperBack"),
("Instant MDX Queries for SQL Server 2012", "Nicholas Emond", "16.99", "Out of Stock", "PaperBack"),
("Instant SQL Server Analysis Services 2012 Cube Security", "Satya SK Jayanty", "13.99", "Out of Stock", "PaperBack"),
("Inside Microsoft SQL Server 2008 T-SQL Programming", "Itzik Ben-Gan", "41.38", "Out of Stock", "PaperBack"),
("Inside Microsoft SQL Server 2008 T-SQL Querying", "Itzik Ben-Gan", "34.48", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 MDX Step by Step", "Bryan Smith", "34.48", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Reporting Services Step by Step", "Stacia Misner", "34.48", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 T-SQL Fundamentals", "Itzik Ben-Gan", "34.48", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Analysis Services Step by Step", "Hitachi Consulting", "34.48", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Internals", "Kalen Delaney", "41.38", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Step by Step", "Mike Hotek", "34.48", "Out of Stock", "PaperBack"),
("Microsoft SQL Server 2008 Administrator's Pocket Consultant", "William Stanek", "31.03", "In Stock", "eBook"),
("Microsoft SQL Server 2005 Integration Services Step by Step", "Paul Turley", "31.03", "In Stock", "eBook"),
("Programming Microsoft SQL Server 2008", "Andrew Brust", "41.38", "In Stock", "eBook"),
("Microsoft SQL Server 2012 Integration Services", "Wee-Hyong Tok", "41.38", "In Stock", "eBook"),
("Microsoft SQL Server 2012 Reporting Services", "Stacia Misner", "43.09", "In Stock", "eBook"),
("Microsoft SQL Server 2012 Step by Step", "Patrick LeBlanc", "34.48", "In Stock", "eBook"),
("Microsoft SQL Server 2012 High-Performance T-SQL Using Window Functions", "Itzik Ben-Gan", "25.85", "In Stock", "eBook"),
("Microsoft SQL Server 2012 Pocket Consultant", "William Stanek", "27.58", "In Stock", "eBook"),
("Microsoft SQL Server 2012 T-SQL Fundamentals", "Itzik Ben-Gan", "34.48", "In Stock", "eBook"),
("SQL Server Datenbanken Entwickeln, Verwalten Und Verstehen", "Dullnigg Laurenz Josef", "46.00", "In Stock", "eBook"),
("Smart Business Intelligence Solutions with Microsoft SQL Server 2008", "Lynn Langit", "34.48", "In Stock", "eBook"),
("Microsoft SQL Server 2012 Analysis Services", "Alberto Ferrari", "41.38", "In Stock", "eBook"),
("Programming Microsoft SQL Server 2012", "Andrew Brust", "41.38", "In Stock", "eBook"),
("Securing SQL Server", "Denny Cherry", "43.06", "In Stock", "eBook"),
("Microsoft SQL Server 2014 Unleashed", "Ray Rankins", "41.38", "In Stock", "eBook"),
("Oracle Database 12C SQL Certified Expert Exam Guide (Exam 1z0-047)", "Steve O'Hearn", "47.91", "In Stock", "eBook"),
("SQL: A Beginner's Guide", "Andy Oppel", "30.99", "In Stock", "eBook"),
("Expert Performance Indexing in SQL Server 2016", "Jason Strate", "29.50", "In Stock", "eBook"),
("SQL/XML", "Michael Wagner", "49.90", "Out of Stock", "PaperBack"),
("SQL per principianti", "Preston Prescott", "2.58", "Out of Stock", "PaperBack"),
("Oracle 10g Developer", "Joan Casteel", "74.99", "Out of Stock", "PaperBack"),
("SQL Server 2000 XML Distilled", "Kevin Williams", "35.50", "Out of Stock", "PaperBack"),
("Code Centric", "Garth Wells", "72.00", "Out of Stock", "PaperBack"),
("Building a Data Warehouse", "Vincent Rainardi", "55.45", "Out of Stock", "PaperBack"),
("Pro SQL Server 2005 Service Broker", "Klaus Aschenbrenner", "39.49", "Out of Stock", "PaperBack"),
("SQL Server 2008 Transact-SQL Recipes", "Joseph Sack", "47.49", "Out of Stock", "PaperBack"),
("Pro SQL Server 2008 Service Broker", "Klaus Aschenbrenner", "55.41", "Out of Stock", "PaperBack"),
("SQL Server 2000 Fast Answers for DBA and Developers", "Joseph Sack", "77.96", "Out of Stock", "PaperBack"),
("Foundations of SQL Server 2005 Business Intelligence", "Lynn Langit", "39.49", "Out of Stock", "PaperBack"),
("Pro SQL Server 2008 Administration", "Ken Simmons", "39.49", "Out of Stock", "PaperBack"),
("SQL Server", "Brennan Pike", "32.12", "Out of Stock", "PaperBack"),
("Pro SQL Server 2005 Replication", "Paul Sujoy", "74.93", "Out of Stock", "PaperBack"),
("Introducing SQL Server 2015", "Mike McQuillan", "39.99", "Out of Stock", "PaperBack"),
("Pro SQL Server Wait Statistics 2015", "Enrico van de Laar", "29.50", "Out of Stock", "PaperBack"),
("Expert SQL Server in-Memory OLTP 2015", "Dmitri Korotkevitch", "29.50", "Out of Stock", "PaperBack"),
("SQL Mit Oracle", "Wolf-Michael K Hler", "36.99", "Out of Stock", "PaperBack"),
("Data Wrangling 2016", "Patrick Houlihan", "29.50", "In Stock", "PaperBack"),
("Microsoft SQL Server 2012 with Hadoop", "Debarchan Sarkar", "9.99", "In Stock", "PaperBack"),
("Oracle PL/SQL Programming", "Steven Feuerstein", "43.99", "In Stock", "PaperBack"),
("SQL Server 2014 Development Essentials", "Basit A. Masood-Al-Farooq", "19.99", "In Stock", "PaperBack"),
("Microsoft SQL Server 2014 Business Intelligence Development", "Reza Rad", "29.50", "In Stock", "PaperBack"),
("Microsoft Sql Server 7.0 CD-Rom (in Text)", "Kroenke", "13.46", "In Stock", "PaperBack"),
("SQL Server 2012 Reporting Services Blueprints", "Mickey Stuewe", "23.99", "In Stock", "PaperBack"),
("SQL para Principiantes", "Preston Prescott", "2.58", "In Stock", "PaperBack"),
("SQL para Iniciantes", "Preston Prescott", "2.58", "In Stock", "PaperBack"),
("Getting Started with SQL", "Thomas Nield", "24.50", "In Stock", "PaperBack"),
("SQL and Relational Theory", "C. J. Date", "28.50", "In Stock", "PaperBack"),
("Oracle PL/SQL Language Pocket Reference", "Steven Feuerstein", "11.20", "In Stock", "PaperBack"),
("Sams Teach Yourself Oracle PL/SQL in 10 Minutes", "Ben Forta", "20.68", "In Stock", "PaperBack"),
("PL/SQL", "Gabi Turscher", "46.99", "In Stock", "PaperBack"),
("The Definitive Guide to DAX", "Alberto Ferrari", "34.48", "In Stock", "PaperBack"),
("T-SQL in One Hour a Day, Sams Teach Yourself", "Alison Balter", "27.58", "In Stock", "PaperBack"),
("SQL Server 2005 Practical Troubleshooting", "Ken Henderson", "41.38", "In Stock", "PaperBack"),
("Advanced Data Management", "Lena Wiese", "40.00", "In Stock", "PaperBack");
